version: "3.8"

services:
  node1:
    image: ruimarinho/bitcoin-core:24
    container_name: node1
    ports:
      - "18443:18443"  # RPC
      - "18444:18444"  # P2P
    volumes:
      - ./node1:/bitcoin/.bitcoin
    command: [
      "bitcoind",
      "-regtest",
      "-printtoconsole",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0",
      "-rpcuser=admin",
      "-rpcpassword=pass",
      "-txindex=1",
      "-server",
      "-daemon=0",
      "-fallbackfee=0.0001"
    ]

  node2:
    image: ruimarinho/bitcoin-core:24
    container_name: node2
    ports:
      - "18445:18443"
      - "18446:18444"
    volumes:
      - ./node2:/bitcoin/.bitcoin
    command: [
      "bitcoind",
      "-regtest",
      "-printtoconsole",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=0.0.0.0",
      "-rpcuser=admin",
      "-rpcpassword=pass",
      "-txindex=1",
      "-server",
      "-daemon=0",
      "-fallbackfee=0.0001"
    ]
